# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec — CV Matcher (Mode IA Locale)
# Commande : pyinstaller cv_matcher.spec --clean --noconfirm

block_cipher = None

a = Analysis(
    ['launcher.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('../frontend', 'frontend'),   # Interface web incluse dans le bundle
    ],
    hiddenimports=[
        # ── tkinter ──
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        # ── urllib (vérification Ollama) ──
        'urllib.request',
        'urllib.error',
        'urllib.parse',
        # ── uvicorn ──
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.websockets.wsproto_impl',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        # ── starlette / fastapi ──
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.staticfiles',
        'starlette.responses',
        'anyio',
        'anyio._backends._asyncio',
        'anyio.from_thread',
        # ── Parsers de documents ──
        'pdfplumber',
        'pdfminer',
        'pdfminer.high_level',
        'pdfminer.layout',
        'pdfminer.pdftypes',
        'pdfminer.pdfpage',
        'pdfminer.pdfinterp',
        'pdfminer.converter',
        'pdfminer.pdfparser',
        'pdfminer.pdfdocument',
        'pdfminer.cmapdb',
        'docx',
        'docx.oxml',
        'docx.oxml.ns',
        'docx.shared',
        'striprtf.striprtf',
        'bs4',
        'bs4.builder',
        'bs4.builder._htmlparser',
        'odf',
        'odf.text',
        'odf.teletype',
        'odf.opendocument',
        'openpyxl',
        'openpyxl.styles',
        'pptx',
        'pptx.util',
        'PIL',
        'PIL.Image',
        # ── SQLAlchemy ──
        'sqlalchemy',
        'sqlalchemy.orm',
        'sqlalchemy.ext.declarative',
        'sqlalchemy.dialects',
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.dialects.sqlite.pysqlite',
        'sqlalchemy.sql.sqltypes',
        # ── Upload fichier ──
        'multipart',
        'python_multipart',
        # ── Async I/O ──
        'aiofiles',
        'aiofiles.os',
        'aiofiles.threadpool',
        # ── HTTP (client Ollama / OpenAI) ──
        'httpx',
        'httpcore',
        'httpcore._sync',
        'httpcore._async',
        'h11',
        # ── OpenAI SDK ──
        'openai',
        'openai.resources',
        'openai.resources.chat',
        # ── Divers ──
        'certifi',
        'charset_normalizer',
        'dotenv',
        'python_dotenv',
        'pydantic',
        'pydantic.v1',
        'sniffio',
        'exceptiongroup',
        'email',
        'email.message',
        'csv',
        're',
        # ── Modules applicatifs ──
        'app',
        'app.main',
        'app.config',
        'app.database',
        'app.models',
        'app.models.db_models',
        'app.models.schemas',
        'app.services',
        'app.services.document_parser',
        'app.services.ai_service',
        'app.routers',
        'app.routers.cv_router',
        'app.routers.job_router',
        'app.routers.match_router',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib', 'numpy', 'pandas',
        'torch', 'tensorflow', 'scipy', 'sklearn',
        'IPython', 'notebook', 'jupyter',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='CVMatcher',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,      # Pas de fenêtre console noire
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='CVMatcher',
)
